lst=["Mango", "Apple", "Orange", "Grapes","Pomegranate"]
print("The length of this list is:",len(lst))
print(lst[0])
print(lst[-1])
lst.append("Guava")
print("Updated List", lst)
lst.remove("Apple")
print("Updated List", lst)
lst.sort()
print("Updated List", lst)
lst.pop(-1)
lst.reverse()
print("Reversed List", lst)
print("Mutiplication on a list: ",lst*2)
print(lst[:4])
lst.clear()
print("Updated List", lst)